---
- name: This is my 1st play
  hosts: web
  tasks:
     - name: INstall apache server
       yum:
         name: httpd
         state: present

     - name: Start and enable service.
       service:
         name: httpd
         state: started 

     - name: Deploy index.html 
       copy:
         content: "This is my web server\n"
         dest: /var/www/html/index.html 
...
